CREATE TABLE CALCULATOR(
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  FNUMBER VARCHAR(250) NOT NULL,
    SNUMBER VARCHAR(250) NOT NULL,
      RESULT VARCHAR(250) NOT NULL,
        OPERATOR VARCHAR(250) NOT NULL,
);